version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/app

hooks:
  BeforeInstall:
    - location: deploy/scripts/install_dependencies.sh
      timeout: 300
      runas: ubuntu

  AfterInstall:
    - location: deploy/scripts/setup_backup.sh
      timeout: 60
      runas: ubuntu

  ApplicationStart:
    - location: deploy/scripts/start_docker.sh
      timeout: 300
      runas: ubuntu
